version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ledger-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Any .sql/.sh in this folder runs once at first startup
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: ledger-adminer
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: